# Use a Debian-based Rust image to build and test the application
FROM rust:1.76.0-bookworm as tester
WORKDIR /usr/src/ActionListener

# Install build dependencies required for your application and tests
# This might include additional tools and libraries needed during the build or test phase
RUN apt-get update && apt-get install -y libssl-dev pkg-config gcc

# Copy your entire application source code into the Docker image
COPY . .

# Build the application to ensure it compiles without any issues
RUN cargo build --release

# Run the tests
# The container's main purpose is to run tests, so we use CMD instead of RUN to make the test command the default action of the container
CMD ["cargo", "test", "--", "--nocapture"]