name: Build Packages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  compile:
    name: Compile
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    # Set an environment variable based on the OS
    env:
      DEPENDS_SETUP: ${{ (matrix.os == 'ubuntu-latest' && 'true') || 'false' }}
      ARTIFACT_NAME: ${{ (matrix.os == 'windows-latest' && 'actions_organizer.exe') || 'actions_organizer' }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable

      - name: Depends install
        if: ${{ env.DEPENDS_SETUP == 'true' }}
        run: |
          sudo apt update
          sudo apt install -qy libgtk-3-dev

      - name: Build | Compile
        run: |
          cargo build --release

      - name: Archive builds
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OS_NAME }}-build
          path: target/release/${{ env.ARTIFACT_NAME }}
            
