name: Build Packages

on:
  push:
    branches:
      - master

jobs:
  compile:
    name: Compile
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    # Set an environment variable based on the OS
    env:
      DEPENDS_SETUP: ${{ (matrix.os == 'ubuntu-latest' && 'true') || 'false' }}
      ARTIFACT_NAME: ${{ (matrix.os == 'windows-latest' && 'ActionAllegro.exe') || 'ActionAllegro' }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable

      - name: Depends install
        if: ${{ env.DEPENDS_SETUP == 'true' }}
        run: |
          sudo apt update
          sudo apt install -qy libgtk-3-dev

      - name: Build | Compile
        run: |
          cargo build --release

      - name: Archive builds
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: target/release/${{ env.ARTIFACT_NAME }}
            
  release:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest-build
          path: artifacts/ubuntu-latest
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: macOS-latest-build
          path: artifacts/macOS-latest
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: windows-latest-build
          path: artifacts/windows-latest

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset-ubuntu 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./artifacts/ubuntu-latest/ActionAllegro
          asset_name: ActionAllegro-ubuntu-latest
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-release-asset-macos 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./artifacts/macOS-latest/ActionAllegro
          asset_name: ActionAllegro-macOS-latest
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-release-asset-windows 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./artifacts/windows-latest/ActionAllegro.exe
          asset_name: ActionAllegro-windows-latest.exe
          asset_content_type: application/octet-stream