name: Test ActionAllegro
on:
  pull_request:
    types:
      - opened
      - edited
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker test container
      run: docker build -t madeofpendletonwool/allegro-test . -f dockerfile-test
    - uses: rustsec/audit-check@v1.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests in the Docker container
      run: docker run madeofpendletonwool/allegro-test

  cargo-checkmate:
    uses: cargo-checkmate/cargo-checkmate/.github/workflows/callee.yaml@gh-callee-v1